language: node_js

node_js:
    - "14"

sudo: false

git:
    submodules: false

before_script:
    # Install validation tools
    - make install

script:
    # Run tests
    - make build
    - make bundle
    - make test

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/3a86d311166c7f6df3ec

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
